const products = [
 {
  "index": 0,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "04333",
  "newCode": "tbd",
  "volume": 289,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD",
  "size": "Adult"
 },
 {
  "index": 1,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "44333",
  "newCode": "tbd",
  "volume": 289,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 2,
  "component": "redCells",
  "category": "Red Cells - Frozen",
  "pack": 0,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "06460",
  "newCode": "tbd",
  "volume": 292,
  "shelfLife": 1,
  "text": "RED CELLS THAWED AND WASHED, LD MANUAL PREPARATION",
  "size": "Adult"
 },
 {
  "index": 3,
  "component": "redCells",
  "category": "Red Cells - Frozen",
  "pack": 0,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "54263",
  "newCode": "tbd",
  "volume": 295,
  "shelfLife": 3,
  "text": "RED CELLS THAWED AND WASHED, LD CLOSED SYSTEM PREPARATION",
  "size": "Adult"
 },
 {
  "index": 4,
  "component": "redCells",
  "category": "Red Cells - Washed",
  "pack": 0,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "46531",
  "newCode": "tbd",
  "volume": 278,
  "shelfLife": 14,
  "text": "RED CELLS WASHED, LD. MANUAL WASH IN SAGM",
  "size": "Adult"
 },
 {
  "index": 5,
  "component": "redCells",
  "category": "Red Cells - Washed",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "46532",
  "newCode": "tbd",
  "volume": 278,
  "shelfLife": 2,
  "text": "RED CELLS WASHED, LD, IRRADIATED. MANUAL WASH IN SAGM",
  "size": "Adult"
 },
 {
  "index": 6,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54288",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD",
  "size": "Adult"
 },
 {
  "index": 7,
  "component": "platelets",
  "category": "Platelets",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54289",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD",
  "size": "Adult"
 },
 {
  "index": 8,
  "component": "platelets",
  "category": "Platelets",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54290",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD",
  "size": "Adult"
 },
 {
  "index": 9,
  "component": "platelets",
  "category": "Platelets",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54291",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD",
  "size": "Adult"
 },
 {
  "index": 10,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54292",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 11,
  "component": "platelets",
  "category": "Platelets",
  "pack": 1,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54293",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 12,
  "component": "platelets",
  "category": "Platelets",
  "pack": 2,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54294",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 13,
  "component": "platelets",
  "category": "Platelets",
  "pack": 3,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54295",
  "newCode": "tbd",
  "volume": 217,
  "shelfLife": 7,
  "text": "PLATELETS, APHERESIS, LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 14,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 1,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "54243",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION PACK 1 LD",
  "size": "Adult"
 },
 {
  "index": 15,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 2,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "54244",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION PACK 2 LD",
  "size": "Adult"
 },
 {
  "index": 16,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 3,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "54245",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION PACK 3 LD",
  "size": "Adult"
 },
 {
  "index": 17,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 0,
  "irr": false,
  "special": true,
  "availability": true,
  "oldCode": "54246",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION LD",
  "size": "Adult"
 },
 {
  "index": 18,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 1,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "54233",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION, IRRADIATED, PACK 1 LD",
  "size": "Adult"
 },
 {
  "index": 19,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 2,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "54234",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION, IRRADIATED, PACK 2 LD",
  "size": "Adult"
 },
 {
  "index": 20,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 3,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "54235",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS, APHERESIS IN ADDITIVE SOLUTION, IRRADIATED, PACK 3 LD",
  "size": "Adult"
 },
 {
  "index": 21,
  "component": "platelets",
  "category": "Platelets - Washed",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "54236",
  "newCode": "tbd",
  "volume": 207,
  "shelfLife": 1,
  "text": "PLATELETS APHERESIS IN ADDITIVE SOLUTION, IRRADIATED, LD",
  "size": "Adult"
 },
 {
  "index": 22,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54477",
  "newCode": "tbd",
  "volume": 294,
  "shelfLife": 7,
  "text": "PLATELETS POOLED IN ADDITIVE SOLUTION AND PLASMA, LD",
  "size": "Adult"
 },
 {
  "index": 23,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54478",
  "newCode": "tbd",
  "volume": 294,
  "shelfLife": 7,
  "text": "PLATELETS POOLED IN ADDITIVE SOLUTION AND PLASMA, IRRADIATED, LD",
  "size": "Adult"
 },
 {
  "index": 24,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "18300",
  "newCode": "tbd",
  "volume": 264,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD",
  "size": "Adult"
 },
 {
  "index": 25,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "18320",
  "newCode": "tbd",
  "volume": 264,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD",
  "size": "Adult"
 },
 {
  "index": 26,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "18321",
  "newCode": "tbd",
  "volume": 264,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD",
  "size": "Adult"
 },
 {
  "index": 27,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "18322",
  "newCode": "tbd",
  "volume": 264,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD",
  "size": "Adult"
 },
 {
  "index": 28,
  "component": "cryo",
  "category": "Cryoprecipitate",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "10190",
  "newCode": "tbd",
  "volume": 229,
  "shelfLife": 1095,
  "text": "CRYOPRECIPITATE, POOLED, LD",
  "size": "Adult"
 },
 {
  "index": 29,
  "component": "redCells",
  "category": "Red Cells - IUT",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "40018",
  "newCode": "tbd",
  "volume": 251,
  "shelfLife": 1,
  "text": "RED CELLS, CPD, LD, IRRADIATED, FOR INTRAUTERINE TRANSFUSION",
  "size": "Adult"
 },
 {
  "index": 30,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56830",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 31,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56831",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 32,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56832",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 33,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 4,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56833",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 34,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 5,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56834",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 35,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 6,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "56835",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 36,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 1,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46830",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 37,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 2,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46831",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 38,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 3,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46832",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 39,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 4,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46833",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 40,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 5,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46834",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 41,
  "component": "redCells",
  "category": "Red Cells",
  "pack": 6,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "46835",
  "newCode": "tbd",
  "volume": 47,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 42,
  "component": "redCells",
  "category": "Red Cells - Neonatal Exchange",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "40350",
  "newCode": "tbd",
  "volume": 362,
  "shelfLife": 1,
  "text": "RED CELLS (CPD), LD, IRRADIATED FOR EXCHANGE TRANSFUSION",
  "size": "Adult"
 },
 {
  "index": 43,
  "component": "redCells",
  "category": "Red Cells - LVT",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54481",
  "newCode": "tbd",
  "volume": 289,
  "shelfLife": 35,
  "text": "RED CELLS IN ADDITIVE SOLUTION, LD FOR NEONATES AND INFANTS",
  "size": "Adult"
 },
 {
  "index": 44,
  "component": "redCells",
  "category": "Red Cells - LVT",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54482",
  "newCode": "tbd",
  "volume": 289,
  "shelfLife": 14,
  "text": "RED CELLS IN ADDITIVE SOLUTION, LD FOR NEONATES AND INFANTS, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 45,
  "component": "platelets",
  "category": "Platelets - IUT",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": true,
  "oldCode": "42964",
  "newCode": "tbd",
  "volume": 96,
  "shelfLife": 1,
  "text": "PLATELETS, HYPERCONCENTRATED, IRRADIATED, FOR INTRAUTERINE TRANSFUSION",
  "size": "Adult"
 },
 {
  "index": 46,
  "component": "platelets",
  "category": "Platelets",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30031",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 47,
  "component": "platelets",
  "category": "Platelets",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30032",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 48,
  "component": "platelets",
  "category": "Platelets",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30033",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 49,
  "component": "platelets",
  "category": "Platelets",
  "pack": 4,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30034",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 50,
  "component": "platelets",
  "category": "Platelets",
  "pack": 5,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30035",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 51,
  "component": "platelets",
  "category": "Platelets",
  "pack": 6,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30036",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 52,
  "component": "platelets",
  "category": "Platelets",
  "pack": 7,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30037",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 53,
  "component": "platelets",
  "category": "Platelets",
  "pack": 8,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "30038",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 54,
  "component": "platelets",
  "category": "Platelets",
  "pack": 1,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30051",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 55,
  "component": "platelets",
  "category": "Platelets",
  "pack": 2,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30052",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 56,
  "component": "platelets",
  "category": "Platelets",
  "pack": 3,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30053",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 57,
  "component": "platelets",
  "category": "Platelets",
  "pack": 4,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30054",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 58,
  "component": "platelets",
  "category": "Platelets",
  "pack": 5,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30055",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 59,
  "component": "platelets",
  "category": "Platelets",
  "pack": 6,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30056",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 60,
  "component": "platelets",
  "category": "Platelets",
  "pack": 7,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30057",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 61,
  "component": "platelets",
  "category": "Platelets",
  "pack": 8,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "30058",
  "newCode": "tbd",
  "volume": 63,
  "shelfLife": 7,
  "text": "PLATELETS IN PLASMA AND ADDITIVE SOLUTION, LD IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 62,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "69601",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 63,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "69602",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 64,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "69603",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 65,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 4,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "69604",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 66,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 5,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59711",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 67,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 6,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59712",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 68,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 7,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59713",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 69,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 8,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59714",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 70,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 9,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59715",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 71,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 10,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59716",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 72,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 11,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59717",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 73,
  "component": "ffp",
  "category": "Fresh Frozen Plasma",
  "pack": 12,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "59718",
  "newCode": "tbd",
  "volume": 65,
  "shelfLife": 1095,
  "text": "FRESH FROZEN PLASMA, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 74,
  "component": "cryo",
  "category": "Cryoprecipitate",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "29981",
  "newCode": "tbd",
  "volume": 53,
  "shelfLife": 1095,
  "text": "CRYOPRECIPITATE, LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 75,
  "component": "granulocytes",
  "category": "Granulocytes",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54395",
  "newCode": "tbd",
  "volume": 222,
  "shelfLife": 0,
  "text": "GRANULOCYTES, POOLED, IN ADDITIVE SOLUTION \/ PLASMA MIX, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 76,
  "component": "platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "12030",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD",
  "size": "Adult"
 },
 {
  "index": 77,
  "component": "platelets",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58340",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD",
  "size": "Adult"
 },
 {
  "index": 78,
  "component": "platelets",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58341",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD",
  "size": "Adult"
 },
 {
  "index": 79,
  "component": "platelets",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58342",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD",
  "size": "Adult"
 },
 {
  "index": 80,
  "component": "platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "42030",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 81,
  "component": "platelets",
  "pack": 1,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48340",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 82,
  "component": "platelets",
  "pack": 2,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48341",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 83,
  "component": "platelets",
  "pack": 3,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48342",
  "newCode": "tbd",
  "volume": 199,
  "shelfLife": 5,
  "text": "PLATELETS APHERESIS LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 84,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": true,
  "oldCode": "54232",
  "newCode": "tbd",
  "volume": 294,
  "shelfLife": 5,
  "text": "PLATELETS POOLED IN PLASMA\/ADDITIVE MIXTURE LD",
  "size": "Adult"
 },
 {
  "index": 85,
  "component": "platelets",
  "category": "Platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": true,
  "oldCode": "54242",
  "newCode": "tbd",
  "volume": 294,
  "shelfLife": 5,
  "text": "PLATELETS POOLED IN PLASMA\/ADDITIVE MIX, IRRADIATED LD",
  "size": "Adult"
 },
 {
  "index": 86,
  "component": "platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "12769",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 5,
  "text": "PLATELETS POOLED, LD",
  "size": "Adult"
 },
 {
  "index": 87,
  "component": "platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "12789",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 7,
  "text": "PLATELETS POOLED, LD, EXTENDED LIFE",
  "size": "Adult"
 },
 {
  "index": 88,
  "component": "platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "54296",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 7,
  "text": "PLATELETS POOLED, LD, EXTENDED LIFE, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 89,
  "component": "platelets",
  "pack": 0,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "54247",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 1,
  "text": "PLATELETS POOLED IN ADDITIVE SOLUTION",
  "size": "Adult"
 },
 {
  "index": 90,
  "component": "platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "54237",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 1,
  "text": "PLATELETS POOLED IN ADDITIVE SOLUTION, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 91,
  "component": "platelets",
  "pack": 0,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "42769",
  "newCode": "tbd",
  "volume": 298,
  "shelfLife": 5,
  "text": "PLATELETS POOLED, LD, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 92,
  "component": "platelets",
  "pack": 1,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58231",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 01 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 93,
  "component": "platelets",
  "pack": 2,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58232",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 02 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 94,
  "component": "platelets",
  "pack": 3,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58233",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 03 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 95,
  "component": "platelets",
  "pack": 4,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58234",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 04 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 96,
  "component": "platelets",
  "pack": 5,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58235",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 05 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 97,
  "component": "platelets",
  "pack": 6,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58236",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 06 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 98,
  "component": "platelets",
  "pack": 7,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58237",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 07 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 99,
  "component": "platelets",
  "pack": 8,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "58238",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 08 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 100,
  "component": "platelets",
  "pack": 9,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "50778",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 09 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 101,
  "component": "platelets",
  "pack": 10,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "50779",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 10 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 102,
  "component": "platelets",
  "pack": 11,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "50780",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 11 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 103,
  "component": "platelets",
  "pack": 12,
  "irr": false,
  "special": false,
  "availability": false,
  "oldCode": "50781",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 12 LD FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 104,
  "component": "platelets",
  "pack": 1,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48231",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 01 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 105,
  "component": "platelets",
  "pack": 2,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48232",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 02 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 106,
  "component": "platelets",
  "pack": 3,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48233",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 03 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 107,
  "component": "platelets",
  "pack": 4,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48234",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 04 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 108,
  "component": "platelets",
  "pack": 5,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48235",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 05 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 109,
  "component": "platelets",
  "pack": 6,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48236",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 06 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 110,
  "component": "platelets",
  "pack": 7,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48237",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 07 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 111,
  "component": "platelets",
  "pack": 8,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "48238",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 08 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 112,
  "component": "platelets",
  "pack": 9,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "40778",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 09 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 113,
  "component": "platelets",
  "pack": 10,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "40779",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 10 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 114,
  "component": "platelets",
  "pack": 11,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "40780",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 11 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 115,
  "component": "platelets",
  "pack": 12,
  "irr": true,
  "special": false,
  "availability": false,
  "oldCode": "40781",
  "newCode": "tbd",
  "volume": 50,
  "shelfLife": 5,
  "text": "PLATELETS, APHERESIS, PACK 12 LD, IRRADIATED FOR NEONATAL USE",
  "size": "Neonatal"
 },
 {
  "index": 116,
  "component": "granulocytes",
  "category": "Granulocytes",
  "pack": 0,
  "irr": true,
  "special": true,
  "availability": false,
  "oldCode": "46460",
  "newCode": "tbd",
  "volume": 56,
  "shelfLife": 0,
  "text": "LEUCOCYTES, BUFFY COAT, IRRADIATED",
  "size": "Adult"
 },
 {
  "index": 117,
  "component": "redCells",
  "category": "Red Cells - Autologous",
  "pack": 0,
  "irr": false,
  "special": true,
  "availability": false,
  "oldCode": "30002",
  "newCode": "tbd",
  "volume": 451,
  "shelfLife": 35,
  "text": "WHOLE BLOOD (CPDA1) AUTOLOGOUS",
  "size": "Adult",
 }
];